### ISSUE TITLE
Use setup.py for installation

### ISSUE THREAD

**Issue by Benjamin-Lee** [AliYoussef96/BCAW-Tool#1]
Currently, the README lists the packages that are required to use BCAW. To make installation easier, would it be possible to make BCAW use a `setup.py` file?

[This repo](https://github.com/kennethreitz/setup.py) has a really good example you can add to your repo. All you'd need to do is fill out the metadata at the top of the file. 

Using a `setup.py` has another advantage: you can upload it to [PyPI](https://pypi.org) so anyone can `pip install` it!

**Comment by AliYoussef96** [comment]
[setup.py](https://github.com/AliYoussef96/BCAW-Tool/blob/master/setup.py)
Also, BCAWT now can be installed directly using 
```
pip install BCAWT
```
