### ISSUE TITLE
Use list of fasta files as argument to BCAW?

### ISSUE THREAD

**Issue by Benjamin-Lee** [AliYoussef96/BCAW-Tool#10]
The arguments for `BCAW` seem like they could be simplified:

https://github.com/AliYoussef96/BCAW-Tool/blob/e7c1498156f4bec21a82aaad011342ed60c2abd9/Source%20Code/BCAWT.py#L8

For example, would it be possible to have `input_the_main_fasta_file` (which is a long variable name, by the way) be either a single FASTA file or a list of FASTA files? That would allow you to eliminate the need for a text file option. Additionally, would it be possible to make the input file argument accept a file-like object (such as [how Biopython does it](http://biopython.org/DIST/docs/api/) for FASTA files) as well a string of the file's path? 

You may also be interested in using [pathlib](https://docs.python.org/3/library/pathlib.html) (part of the standard library) to make handling file paths a bit easier.

**Comment by AliYoussef96** [comment]
**After modifications.**
https://github.com/AliYoussef96/BCAW-Tool/blob/dbbd63579c171cacea431658d784b70e2374e26d/BCAWT/BCAWT.py#L1

1. List of fasta files.

The arguments now could be both a single fasta file or a list of fasta files
example:
```
from BCAWT import BCAWT
BCAWT.BCAW(['Ecoli.fasta','Lacidophilus.fasta'],'result_folder',genetic_code_=11,Auto=True)
```
2. file-like object.

The arguments now could be a string of the file's path as well a file-like object
example:
```
from BCAWT import BCAWT
file_fasta = open("Ecoli.fasta",'r')
BCAWT.BCAW([file_fasta],'result_folder',genetic_code_=11,Auto=True)
```

3- pathlib.

pathlib now used to handle file paths

https://github.com/AliYoussef96/BCAW-Tool/blob/c02e8ac1fe5b9acec201cbababfec13de329ad88/BCAWT/BCAWT.py#L60
https://github.com/AliYoussef96/BCAW-Tool/blob/c02e8ac1fe5b9acec201cbababfec13de329ad88/BCAWT/BCAWT.py#L90
