### ISSUE TITLE
troubles with running the BCAW tool

### ISSUE THREAD

**Issue by symonovar** [AliYoussef96/BCAW-Tool#14]
Dear Ali, 
I am trying to get working the BCAW tool in my Jupyter notebook and keep on receiving this message:
ImportError                               Traceback (most recent call last)
<ipython-input-43-65a5f7461caf> in <module>
----> 1 BCAWT.BCAW("Ecoli.fasta", "Users\Radka\Documents\PrFJcU", "result", genetic_code_=1, Auto = True)

~\anaconda3\lib\site-packages\BCAWT\BCAWT.py in BCAW(main_fasta_file, save_path, ref_fasta_file, genetic_code_, Auto)
     30     import Bio
     31     from Bio import SeqIO
---> 32     from Bio.Alphabet import IUPAC
     33     from Bio.Seq import Seq
     34     from Bio.SeqUtils import GC

~\anaconda3\lib\site-packages\Bio\Alphabet\__init__.py in <module>
     18 """
     19 
---> 20 raise ImportError(
     21     "Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information."
     22 )

Unfortunately, i cannot get working the GUI neither.

thanks for your help
Radka
radka.symonova@gmail.com

**Comment by AliYoussef96** [comment]
Hi @symonovar, 

Sorry for being late. I updated the package on both PyPI and GitHub.
Just re-install the last version using `pip install BCAWT==1.0.6`, and I believe it will work without any problems now.
