### ISSUE TITLE
Automated testing

### ISSUE THREAD

**Issue by Benjamin-Lee** [AliYoussef96/BCAW-Tool#3]
Per the JOSS review checklist, this project needs automated tests. 

Although you can use whichever system for testing you prefer, if you're unsure where to start, I'd recommend [pytest](https://pytest.org). It would also be a good idea to automate testing using something like [Travis](https://docs.travis-ci.com/user/languages/python/) but, again, there are a [variety of choices](https://github.com/marketplace?category=continuous-integration).

**Comment by AliYoussef96** [comment]
I'm writing now the test I will finish it very soon.

Also, for the BCAW tool, I did BCAWT_auto_test.py.
I did describe how to use this test in [README.md](https://github.com/AliYoussef96/BCAW-Tool/blob/master/README.md) and in the [documentation](https://bcaw-tools-documentation.readthedocs.io/en/latest/Usage.html)

**Comment by AliYoussef96** [comment]
[test.py](https://github.com/AliYoussef96/BCAW-Tool/blob/master/test.py)

**Comment by Benjamin-Lee** [comment]
Fantastic. Would it be possible to use Travis CI (or similar) to automatically run test.py for every commit to make sure nothing breaks?

**Comment by AliYoussef96** [comment]
I used Travis CI to automatically run test.py and it is passed.  
[![Build Status](https://travis-ci.org/AliYoussef96/BCAW-Tool.svg?branch=master)](https://travis-ci.org/AliYoussef96/BCAW-Tool)
