### ISSUE TITLE
Community guidelines

### ISSUE THREAD

**Issue by Benjamin-Lee** [AliYoussef96/BCAW-Tool#4]
JOSS requires a project to have community guidelines. This should be a file called `CONTRIBUTING` with information on how to contribute, report issues or problems with the software, and seek support.

**Comment by Benjamin-Lee** [comment]
[Here](https://mozillascience.github.io/working-open-workshop/contributing/) is a guide for writing a CONTRIBUTING.md file as well as a [template](https://github.com/nayafia/contributing-template/blob/master/CONTRIBUTING-template.md) to make it easier.

**Comment by AliYoussef96** [comment]
Thank you for the useful sources
[CONTRIBUTING.md](https://github.com/AliYoussef96/BCAW-Tool/blob/master/CONTRIBUTING.md)
