### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by Benjamin-Lee** [AliYoussef96/BCAW-Tool#5]
This project should have API docs. I'd recommend using Sphinx and deploying on [Read The Docs](https://readthedocs.org), but there are a variety of options. [Here's](http://www.writethedocs.org/guide/) a good site with information about how to write docs.

**Comment by AliYoussef96** [comment]
[Documentation with API ](https://bcaw-tools-documentation.readthedocs.io/en/latest/)
