### ISSUE TITLE
Setup.py should use biopython, not Bio

### ISSUE THREAD

**Issue by Benjamin-Lee** [AliYoussef96/BCAW-Tool#6]
While the import for Biopython is `bio`, the PyPI identifier for it is `biopython`:

https://github.com/biopython/biopython#for-the-impatient

https://github.com/AliYoussef96/BCAW-Tool/blob/9030aca9b5ecd91f5e33d59e32db5460fb07605d/setup.py#L24

**Comment by AliYoussef96** [comment]
Done:

https://github.com/AliYoussef96/BCAW-Tool/blob/955a1d18c363d6a128769e3f3ae606bd47bd96be/setup.py#L24
