### ISSUE TITLE
Use generator expression for iterating over codons

### ISSUE THREAD

**Issue by Benjamin-Lee** [AliYoussef96/BCAW-Tool#7]
In this line, you're trying to get the codons in the sequence.:

https://github.com/AliYoussef96/BCAW-Tool/blob/e7c1498156f4bec21a82aaad011342ed60c2abd9/Source%20Code/ATCG3.py#L27

While this is correct, it might not be the best way to do it. First of all, `re` adds a lot of overhead. Moreover, it returns a list, meaning that you have to load the whole sequence into memory, even though you're only using one codon at a time.

I suggest using a generator expression like this:

```python
codon = (sequ[i: i+3] for i in range(0, len(sequ), 3))
```

It's also much more performant, as can be seen in this [example notebook](https://nbviewer.jupyter.org/gist/Benjamin-Lee/cf7f70f6007557bf6779b085df830ef9).

**Comment by AliYoussef96** [comment]
Great suggestion, thank you!

Yes, it is obvious that generator expression is much more performant.

I used it everywhere now, also I used **tee** from **itertools** to used it in loops more than one time.

https://github.com/AliYoussef96/BCAW-Tool/blob/af72b53869b8adf9e9206a93ad5abb85c115bceb/BCAWT/ATCG3.py#L29
