### ISSUE TITLE
Move Introduction to codon usage bias.pdf to /docs

### ISSUE THREAD

**Issue by Benjamin-Lee** [AliYoussef96/BCAW-Tool#9]
PDFs are generally less usable than editable text-based files. Additionally, the information contained in `Introduction to codon usage bias.pdf` would be useful to have directly in the docs.

Would it be possible to covert the PDF to RST (possibly using [pandoc](https://pandoc.org) on the source file) and put it on the docs website?

**Comment by AliYoussef96** [comment]
I added the introduction to codon usage bias along with the equations used to the docs.

[![Documentation Status](https://readthedocs.org/projects/bcaw-tools-documentation/badge/?version=latest)](https://bcaw-tools-documentation.readthedocs.io/en/latest/?badge=latest)

**Comment by Benjamin-Lee** [comment]
This looks pretty good. Some notes:

- Citation 15 (Duret and Mouchiroud) seems to have a broken link
- Citation 19 should have DOI 10.1016/0378-1119(90)90491-9
- Citation 21 should have DOI 10.1093/nar/15.3.1281
- Citation 23 appears to be a duplicate of 21.
- Citation 24 (that's me!) should use first initial B.
- Citation 26 is all caps (not sure if intentional) and uses full url as DOI.
- Citation 32 lacks authors and should have DOI 10.1093/oxfordjournals.molbev.a026326
- Citation 33 lacks authors and should have DOI 10.1016/0022-2836(89)90252-0.
- In [this section](https://bcaw-tools-documentation.readthedocs.io/en/latest/intro.html#establish-reference-genes-set), 2 appears not to be indented properly.
- Statement of need should like to the docs page, not the PDF.

**Comment by AliYoussef96** [comment]
I considered all the points mentioned, and I edited it. https://bcaw-tools-documentation.readthedocs.io/en/latest/Intro.html

**Comment by Benjamin-Lee** [comment]
Great! Citation 15 can use doi 10.1073/pnas.96.8.4482 (taken from the link) and then this issue is closed.

**Comment by AliYoussef96** [comment]
Great. I added the doi to citation 15.

**Comment by AliYoussef96** [comment]
Great. I added the doi to citation 15.
